### ISSUE TITLE
Inconsistent triggering when dragging a window to screen edges

### ISSUE THREAD

**Issue by l3nn4rt** [Leleat/Tiling-Assist#23]
### description

Window tiling should not be triggered when the window is close to the top screen edge, but only when the pointer is.
It's not obvious when dragging a window by its decoration (top bar), but it is when dragging with Super key. 

It is now triggered when:

- the pointer is close to bottom / left / right screen edge
- the window is close to top edge

### environment

GNOME Shell: 3.38.2 (Xorg or Wayland)
OS: Arch Linux
Tiling-Assist: commit 66c29d3

### demo

https://streamable.com/7rg4it

**Comment by Leleat** [comment]
Because of the wrong grab position (similiar to what you previously reported), `global.get_pointer()` didn't seem to return the correct mouse (y) position. As a workaround I used the grabbed window's y position to detect when a window is near the top and bottom of a screen. I was working under the assumption that a grab could only be initiated via the title/topbar; didn't know that you could start a grab like that xD.

Since the grab position now seems to work properly, I use `global.get_pointer()` again. After some initial tests, it seems to work reliably now.

**Comment by Leleat** [comment]
One thing I couldn't figure out:

If I grab a window from the maximized state and try to go back to the top bar, there is a weird "barrier", which blocks the window from hitting the topbar. Only after the mouse enters the topbar, does the window snap to the topbar as well. 

Functionally there doesn't seem to be an issue though...

**Comment by l3nn4rt** [comment]
Works perfectly! :top: 

I see that barrier too, and it looks proportional to the distance between the grab point and the bottom of the window decoration:

![barrier](https://user-images.githubusercontent.com/20030650/103807187-58abdd80-5056-11eb-88a3-3edf431dc3a8.png)
