### ISSUE TITLE
How to swap windows?

### ISSUE THREAD

**Issue by cristianvasquez** [Leleat/Tiling-Assist#31]
In an android tablet, one can swap split-screen apps top to bottom or left to right by just tapping the split bar and picking swap.

Question:
What would be a simple way to do something similar with this extension? 

Thanks for the nice work!

**Comment by Leleat** [comment]
>  What would be a simple way to do something similar with this extension?

There is no direct way to swap 2 windows and I don't think it's possible to implement one because my extensions allows for a practically unlimited amount of tiled windows. So I would have no way of knowing which windows the user would want to swap.

But you can use the existing feature to "simulate" a swap.

Via keyboard:
- Use the `Tile to other tiled window` keybinding. Pressing that keybinding will open a preview of your current tiled layout. Pressing a number or clicking a rectangle will tile the focused window to it. If there is free screen space, the dash with the open apps will appear. Here an example:
![key](https://user-images.githubusercontent.com/53054301/108594329-5b962f80-7371-11eb-8a5d-99983d0d2ed0.gif)

Via mouse:
- When DNDing window, you can hold `Ctrl`. If you hover over a tiled window, you can "replace" that hovered window (or split the window if you hover at the sides e. g. top, bottom, left or right). Here another example:
![mouse](https://user-images.githubusercontent.com/53054301/108594397-ba5ba900-7371-11eb-8a32-3636c52e9f94.gif)

**Comment by cristianvasquez** [comment]
Waw!, 

I was not aware of the Ctrl functionality. Thanks for your response!
