### ISSUE TITLE
Toggle whether to display 'fill remaining space' app list

### ISSUE THREAD

**Issue by Turbine1991** [Leleat/Tiling-Assist#32]
Hopefully you're open to small ideas. This is to avoid an extra stage which is somewhat distracting while working.

**Describe your idea**
Add a setting's toggle (like Windows 10), which allows you to hide displaying other open apps following a tile snap.

**Comment by Leleat** [comment]
You can already do that. It's called `Enable Dash`. There is also a keybinding to do that in the `Other` section. Or am I misunderstanding you?

**Comment by Turbine1991** [comment]
> You can already do that. It's called `Enable Dash`. There is also a keybinding to do that in the `Other` section. Or am I misunderstanding you?

I assumed Dash meant something completely different. That solved it! :)

This extension is fantastic, you've done an exceptional job. I'm blown away by how professional the polish is.

How likely is this extension to break between major Gnome releases? If it might work, perhaps adding 3.40 will allow those user's compiling Gnome to enjoy this must have extension.

**Comment by Leleat** [comment]
> How likely is this extension to break between major Gnome releases?

Hard to say in general but my extension *shouldn't* break with most releases as I mostly add stuff on top of the GNOME shell. 

GNOME 40 (btw GNOME uses a new versioning scheme and dropped the 3) is an exception as they switched from GTK3 to GTK4. So the preference window will definitely not work. Functionality should be the same though.

I plan to port my extension to GNOME 40 so that when it's released my extension will be compatible.

PS. If you build GNOME from source right now, you need to add the GNOME versions to the metadata.json of this extension because GNOME recently enabled extension version checks. So currently that means adding `"40.beta"` to `metadata.json`, if you want to try it (I haven't tested my extension yet).
