### ISSUE TITLE
Overlayed icons when tiling to half

### ISSUE THREAD

**Issue by Etamuk** [Leleat/Tiling-Assist#4]
Hello,

I noticed a small issue when tiling a window the left/right side. After  moving the window to the edge a set of icons appears on the other side. This icons are overlaying. Please see my screenshot.
Maybe a screen resolution problem? I am using a 4K screen, 200% scaled.
![Bildschirmfoto von 2020-10-28 12-44-55](https://user-images.githubusercontent.com/20098065/97432354-21190a80-191c-11eb-8d9e-28ea249215fd.png)

**Comment by Leleat** [comment]
Which version of the extensions are you using? The one from gnome's extension website or did you get it from github?

If you got it from the extension's website, when did you download? I had this bug on the first version of the extension (was due an initialization erro). The second version has it fixed. 

The github version has been reworked to allow quarter tiling. But I am sill working on it, so I haven't updated it on the extensions website yet (although it should already be usable).

**Comment by Leleat** [comment]
Nvm, it is a different bug than the one I mentioned.

I tested the scaling on my monitor as well and I get the same problem. I'll fix it .

**Comment by Etamuk** [comment]
Thank you for the quick answer. 
I downloaded it right now from Gnome Extensions site. It should be version 2. 
As I can see, you were able to reproduce it. Thanks.

**Comment by Leleat** [comment]
I've created a branch with this issue fixed:

https://github.com/Leleat/Tiling-Assist/tree/2-column-design

I don't indent to push this fix to the extensions website though since I intend change the 2 column tiling design to a 2x2 grid (like Windows) and I am pretty close to being done with that. So I don't want to submit an update which will be obsolete in just a few days.

So if you want to keep GNOME's 2 column design, you need to manually install this extension. Only changes (compared to the current version on the extension website) I made are in `extension.js`.

**Comment by Etamuk** [comment]
I have copied the modified extension.js to my actually installed version and have to say: it´s working fine now. 
Thank you for this app. 
Let me know if you need help by translating into German (if there will be a preferences dialog with settings in the future).
