### ISSUE TITLE
[QOL] Clean up inconsistencies and settings

### ISSUE THREAD

**Issue by Turbine1991** [Leleat/Tiling-Assist#49]
Some naming consistencies need to be addressed to better identify which feature-set an associated method/data member belongs to. The settings needs a little bit of cleaning up to address readability and aesthetics.

![Screenshot from 2021-03-23 11-00-16](https://user-images.githubusercontent.com/7228980/112064463-dc8e5400-8bc7-11eb-8cf8-a7c4ff2a2010.png)

**Comment by Leleat** [comment]
The new ordering make sense. About the names:
- I've checked GNOME Tweaks now and they capitalize names, so I'll follow that (i. e. your second screenshot). 
- Don't think `Window Padding` is the right choice. Gaps (so like `Tiled Window Gaps`) seems to be more common (see Pop Shell, ShellTile etc.). Googling `tiling window managers window gaps` vs `window paddings` also seem to yield slightly more accurate results.
- How about `Inverse Top Screen Edge Action` since it is not just about maximizing and using screen edge might make it more obvious that it is about DNDing?

Btw I've actually changed the settings ui quite a bit in the rewrite. So I don't think it makes sense to still open a pr for the old settings with just visual changes. Feel free to take a look at the new settings and make suggestions against that. Here is a current screenshot:

![1](https://user-images.githubusercontent.com/53054301/112015541-d21a7e80-8b23-11eb-816f-bfc4bfbc28dc.png)

Changes and the reasoning behind them:

- **Rename Dash to Popup**: I had 2 people say they wanted an option to disable the Dash... even though that setting already existed. Turned out they didn't know what I meant with *Dash*. Dash seems rather a uncommon. Even GNOME doesn't seem to use 'Dash' itself in a user-facing manner. But I couldn't come up with a better name so I decided to go with popup since that is what GNOME shell calls their altTab ("app switcher popup") and in my rewrite 95 % of the functionality of the Dash/Popup comes from altTab.js. As a result I removed the icon size and margin setting. Adding an optional icon size is trivial (and margins via css probably as well) but I don't know how many people actually change the default here... I am going for a "feel as native as possible" with my extension.
- **Remove tooltips / introduce a 'User Guide' tab:** Almost all settings at this point might need tooltip, which is rather ugly. Tooltips can also only explain settings but not all features my extension offers (like holding `Ctrl` when DNDing a window). I tried to explain features in the README on github but apparently not a lot of people read it, so I thought about putting a README into the settings. This way people are very likely to see it. Not sure about the design yet, I am not happy with its current state...
- **'Hidden setttings' page:**  This is just a tab without a name. I don't like adding a setting for every minor detail... So in there I plan to put settings which I don't expect the general user to ever touch (like animations) but which may still be worth being able to configure for select few.

Any thoughts?

**Comment by Turbine1991** [comment]
I agree with all of that. Even though there's also quarter tiling at the top, I think everyone will know what it means, so it's alright.

The pull request will be for more than just settings, it's a small stop gap measure until the recode is released.

**Comment by Leleat** [comment]
Closed by #52.
