### ISSUE TITLE
Default Shortcuts Super+1 to Super+9 for tiling

### ISSUE THREAD

**Issue by fastrizwaan** [Leleat/Tiling-Assist#54]
**Describe your idea**
Put Windows, uses Super keys + numlock number keys, Tiling Assist should also use those keys for keyboard driven tiling,
**Additional context**
 here's the file: https://github.com/negesti/gnome-shell-extensions-negesti/blob/develop/schemas/org.gnome.shell.extensions.org-lab21-putwindow.gschema.xml

I've set these manually:
![Screenshot from 2021-03-29 07-01-35](https://user-images.githubusercontent.com/1161682/112776646-de3f9800-905d-11eb-9aaf-0263ae1df9b0.png)

**Comment by Turbine1991** [comment]
This is a good idea, I'll create a pull request now.

**Comment by Leleat** [comment]
I'm not very into this because there are also a non-insignificant number of people without a dedicated numpad (for example: laptops only start having numpads > 15"). Although I do see the appeal since the physical position of the numbers translate really well into the quarter/half tilings. Since I don't provide any default shortcuts, in the end I am fine with it.

Only concern: are these shortcuts already taken by GNOME? I think Super+number will open an app from the Dash. Does this also apply to the numpad or are they bound to any other action (I can't test it cause I am one of those without a numpad)?

**Comment by fastrizwaan** [comment]
> I'm not very into this because there are also a non-insignificant number of people without a dedicated numpad (for example: laptops only start having numpads > 15"). Although I do see the appeal since the physical position of the numbers translate really well into the quarter/half tilings. Since I don't provide any default shortcuts, in the end I am fine with it.
> 
> Only concern: are these shortcuts already taken by GNOME? I think Super+number will open an app from the Dash. Does this also apply to the numpad or are they bound to any other action (I can't test it cause I am one of those without a numpad)?

No this does not apply to numpad. Gnome uses Super+number above qwertyuiop keys. Super + keypad keys are not used by Gnome.

**Comment by Leleat** [comment]
> No this does not apply to numpad. Gnome uses Super+number above qwertyuiop keys. Super + keypad keys are not used by Gnome.

Alright, thanks. PR by Turbine is merged.
